
"use client";

import type { Prescription } from '@/lib/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Pill, CalendarDays, Trash2, FileDown } from 'lucide-react';
import { format } from 'date-fns';
import { Button } from '../ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import jsPDF from 'jspdf';

interface PrescriptionListItemProps {
  prescription: Prescription;
  patientName: string;
  onDelete: (prescriptionId: string) => void;
  // onEdit: (prescription: Prescription) => void; // For future edit functionality
}

export default function PrescriptionListItem({ prescription, patientName, onDelete }: PrescriptionListItemProps) {
  const handleDownloadPdf = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Prescription Details", 14, 22);
    doc.setLineWidth(0.5);
    doc.line(14, 25, 196, 25); // Horizontal line

    doc.setFontSize(12);
    doc.text(`Patient: ${patientName}`, 14, 35);
    doc.text(`Date Prescribed: ${format(new Date(prescription.datePrescribed), 'MMMM d, yyyy')}`, 14, 42);

    doc.text(`Medication: ${prescription.medicationName}`, 14, 56);
    doc.text(`Dosage: ${prescription.dosage}`, 14, 63);
    
    doc.text("Instructions:", 14, 70);
    const instructionsText = doc.splitTextToSize(prescription.instructions, 170); // Wrap text
    doc.text(instructionsText, 14, 77);

    const finalY = 77 + (instructionsText.length * 7) + 10; // Calculate Y position after instructions
    doc.line(14, finalY, 196, finalY); // Horizontal line
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by PatientPal", 14, finalY + 7);


    doc.save(`prescription_${prescription.medicationName.replace(/\s+/g, '_')}_${patientName.replace(/\s+/g, '_')}.pdf`);
  };
  
  return (
    <Card className="mb-4 shadow-sm">
      <CardHeader className="pb-3">
        <div className="flex justify-between items-start">
            <CardTitle className="text-lg flex items-center gap-2">
            <Pill className="h-5 w-5 text-accent" />
            {prescription.medicationName}
            </CardTitle>
            <div className="flex gap-1">
                <Button variant="ghost" size="icon" onClick={handleDownloadPdf} className="text-primary hover:text-primary/80">
                    <FileDown className="h-4 w-4" />
                </Button>
                 <AlertDialog>
                    <AlertDialogTrigger asChild>
                    <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive/80">
                        <Trash2 className="h-4 w-4" />
                    </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                        <AlertDialogDescription>
                        This action cannot be undone. This will permanently delete the prescription for {prescription.medicationName}.
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={() => onDelete(prescription.id)} className="bg-destructive hover:bg-destructive/90">
                        Delete
                        </AlertDialogAction>
                    </AlertDialogFooter>
                    </AlertDialogContent>
                </AlertDialog>
            </div>
        </div>
        <CardDescription className="flex items-center gap-1 text-xs text-muted-foreground pt-1">
          <CalendarDays className="h-3 w-3" /> Prescribed on: {format(new Date(prescription.datePrescribed), 'MMMM d, yyyy')}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <p className="text-sm"><strong className="font-medium">Dosage:</strong> {prescription.dosage}</p>
        <p className="text-sm mt-1"><strong className="font-medium">Instructions:</strong> {prescription.instructions}</p>
      </CardContent>
    </Card>
  );
}
